#pragma once

enum EventType
{
    EVENT_UNKNOWN = 0,
    EVENT_WINDOW_CLOSE,
    EVENT_WINDOW_RESIZE,
    EVENT_WINDOW_FOCUS,
    EVENT_WINDOW_LOST_FOCUS,
    EVENT_WINDOW_MOVE,
    EVENT_APPLICATION_TICK,
    EVENT_APPLICATION_UPDATE,
    EVENT_APPLICATION_RENDER,
    EVENT_KEYBOARD_PRESS,
    EVENT_KEYBOARD_LONG_PRESS,
    EVENT_KEYBOARD_RELEASE,
    EVENT_MOUSE_CLICK,
    EVENT_MOUSE_RELEASE,
    EVENT_MOUSE_MOVE,
    EVENT_MOUSE_SCROLL,
};
